version: '3.7'

services:

  database:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend

  app:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - backend

networks:
  backend:
